<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMA4jl9y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMA4jl9y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMA4jl9y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMA4jl9y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMA4jl9y\App_KernelDevDebugContainer([
    'container.build_hash' => 'MA4jl9y',
    'container.build_id' => '4193a5ba',
    'container.build_time' => 1588328584,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMA4jl9y');
